# Site-Fit Default Ruleset
# Engineering rules for wastewater/biogas facility site layout
# Override values at request time via rules_override parameter

# Property line and boundary setbacks (meters)
setbacks:
  property_line_default: 7.5
  property_line_front: null    # Uses default if null
  property_line_rear: null     # Uses default if null
  property_line_side: null     # Uses default if null
  wetland_buffer: 15.0
  watercourse_buffer: 30.0

# Equipment-to-boundary setbacks by equipment type (meters)
equipment_to_boundary:
  default: 5.0
  digester: 15.0
  flare: 30.0
  chemical_storage: 10.0
  blower_building: 10.0
  electrical_building: 8.0

# Equipment-to-equipment clearances (meters)
# Format: "type1_to_type2" for specific pairs, "type_to_any" for wildcards
equipment_clearances:
  default: 3.0
  # Digesters - larger clearances for safety and maintenance
  digester_to_any: 10.0
  digester_to_digester: 5.0
  # Flares - significant safety setbacks
  flare_to_any: 75.0
  # Process equipment adjacencies
  aeration_to_clarifier: 5.0
  aeration_to_aeration: 3.0
  clarifier_to_clarifier: 3.0
  # Buildings
  building_to_building: 6.0
  # Tanks
  tank_to_tank: 3.0
  eq_tank_to_tank: 3.0
  # Pump stations
  pump_station_to_any: 3.0

# Fire separation requirements (meters)
# Takes precedence over clearances when larger
fire_separation:
  default: 0.0
  flare_to_any: 75.0
  chemical_storage_to_building: 15.0
  electrical_building_to_digester: 15.0
  fuel_storage_to_any: 30.0
  generator_to_building: 10.0

# Road and vehicle access rules (meters)
access:
  road_width: 6.0
  min_turning_radius: 12.0
  dock_depth: 15.0
  fire_lane_width: 6.0
  max_dead_end_length: 150.0

# Topology constraint weights (soft constraints)
adjacency_preference_weight: 10.0  # Higher = stronger preference for topology adjacencies
flow_direction_weight: 5.0         # Higher = stronger east-west flow preference

# NFPA 820 Hazardous Area Classifications
# Reference: NFPA 820 - Standard for Fire Protection in Wastewater Treatment and Collection Facilities
# Class I, Division 1: Ignitable concentrations of flammable gases/vapors normally exist
# Class I, Division 2: Ignitable concentrations may exist under abnormal conditions
nfpa820_zones:
  # Anaerobic digesters - major source of methane
  digester:
    class_i_div_1_radius: 0.0      # Interior only (not modeled as radius)
    class_i_div_2_radius: 3.0      # 10 ft horizontal from openings
    vertical_above: 0.46           # 18 inches above grade

  # Wet wells - enclosed spaces with potential gas accumulation
  wet_well:
    class_i_div_1_radius: 0.0      # Interior only
    class_i_div_2_radius: 3.0      # 10 ft horizontal
    vertical_above: 0.46

  # Digester gas piping and appurtenances
  digester_gas_piping:
    class_i_div_1_radius: 1.5      # 5 ft from connections/vents
    class_i_div_2_radius: 3.0      # 10 ft from connections/vents

  # Covered primary/secondary clarifiers with gas collection
  covered_clarifier:
    class_i_div_1_radius: 0.0      # Interior only
    class_i_div_2_radius: 3.0      # 10 ft horizontal

  # Odor control systems with potential H2S/methane
  odor_control:
    class_i_div_1_radius: 0.0
    class_i_div_2_radius: 0.9      # 3 ft around vents

  # Gas flares - area during normal operation
  flare:
    class_i_div_1_radius: 1.5      # 5 ft around base
    class_i_div_2_radius: 4.5      # 15 ft around base

# Equipment types that must be located outside hazard zones
hazard_zone_exclusions:
  - electrical_building
  - control_building
  - motor_control_center
  - office
  - laboratory
